GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title" : "Book of Zukk"
}

###

PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title" : "Book of Titann"
}

###

DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json